@startuml

(Dienstleister) --> (Dienstleistung)
(Spender) --> (Spende)
(Randständiger) <-- (Spende)
(Spende) --> (Dienstleistung)

(Dienstleister) .up.> (Ort)
(Randständiger) .up.> (Ort)
(Spender) .up.> (Ort)

@enduml
